services:
  - type: web
    name: novabiz-max
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: NOVABIZ_WHATSAPP
        value: "056-0000000"
      - key: NOVABIZ_BRAND
        value: "NovaBiz"
